const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const demos={
bitemporal:{headline:"Yes, there is a significant change in the selected region.",finding:"The demo compares the two dates and summarizes the most important difference.",metrics:[["Change Detected","−24.6%","Forest Area"],["Confidence","92%","High"],["Area Affected","12.8 km²","Approx."],["Analysis Date",new Date().toLocaleDateString(),"Demo"]],summary:["A large portion of the green area has changed between the two dates.","The highlighted area may represent development, clearing, seasonal change, or another land-cover shift."],task:"Bi-temporal Change Analysis",inputs:"2 imagery files"},
single:{headline:"The selected image contains several clear land-cover types.",finding:"The demo summarizes one image in simple language.",metrics:[["Vegetation","48%","Dominant"],["Built-up","28%","Detected"],["Water","14%","Visible"],["Confidence","96%","High"]],summary:["Vegetation is the largest visible class.","Built-up structures and a transport corridor are also visible."],task:"Single-image VQA / Scene Understanding",inputs:"1 imagery file"},
optical_sar:{headline:"Optical and SAR information complement each other.",finding:"The demo combines both sensor types to create a more complete interpretation.",metrics:[["Built-up","38 ha","Joint view"],["Water","24.2 ha","Joint view"],["Fusion Gain","+28%","Demo"],["Confidence","97%","High"]],summary:["Optical imagery adds visual and spectral context.","SAR adds structural information and can help through cloud cover."],task:"Cross-modal Optical + SAR Analysis",inputs:"2 imagery files"}};
function getState(){return JSON.parse(localStorage.getItem("sqState")||"{}")}function save(v){localStorage.setItem("sqState",JSON.stringify({...getState(),...v}))}
const page=document.documentElement.dataset.page;$$("[data-nav]").forEach(a=>a.classList.toggle("active",a.dataset.nav===page));
if(page==="workspace"){let mode=getState().mode||"bitemporal";function apply(m){mode=m;save({mode:m});$$("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));const c={single:["One image","",false],bitemporal:["Before image","After image",true],optical_sar:["Optical image","SAR image",true]}[m];$("#label1").textContent=c[0];$("#label2").textContent=c[1];$("#upload2").style.display=c[2]?"grid":"none"}$$("[data-mode]").forEach(b=>b.onclick=()=>apply(b.dataset.mode));function file(n){const i=$("#file"+n),p=$("#preview"+n),l=i.closest(".upload-soft");i.onchange=()=>{const f=i.files[0];if(!f)return;$("#name"+n).textContent=f.name;if(f.type.startsWith("image/")){const r=new FileReader();r.onload=e=>{p.src=e.target.result;l.classList.add("has-image");if(e.target.result.length<1800000)save({["img"+n]:e.target.result})};r.readAsDataURL(f)}}}file(1);file(2);$$(".idea-row button").forEach(b=>b.onclick=()=>$("#query").value=b.textContent);$("#runAnalysis").onclick=()=>{const q=$("#query").value.trim();if(!q)return $("#query").focus();$("#runAnalysis").textContent="Analyzing...";save({mode,query:q,result:demos[mode]});setTimeout(()=>location.href="analysis.html",800)};apply(mode)}
if(page==="analysis"){const s=getState(),d=s.result||demos[s.mode||"bitemporal"];$("#headline").textContent=d.headline;$("#finding").textContent=d.finding;$("#metrics").innerHTML=d.metrics.map(m=>`<article><span>${m[0]}</span><b>${m[1]}</b><small>${m[2]}</small></article>`).join("");$("#summary").innerHTML=d.summary.map((x,i)=>`<div><span>0${i+1}</span><p>${x}</p></div>`).join("");$("#techTask").textContent=d.task;$("#techInputs").textContent=d.inputs;$("#techQuery").textContent=s.query||"No query saved";[["statsToggle","statsBody"],["processToggle","processBody"],["techToggle","tech"]].forEach(([b,c])=>$("#"+b).onclick=()=>$("#"+c).classList.toggle("open"))}
if(page==="evidence"){const s=getState();if(s.img1){$("#beforeImg").src=s.img1;$(".before-card").classList.add("has-image")}if(s.img2){$("#afterImg").src=s.img2;$(".after-card").classList.add("has-image")}const regions={development:["New development","The selected demo area shows a strong change between the two dates.","+23.4 ha"],water:["Water variation","The selected demo area shows a change in visible water extent.","−7.8%"],land:["Land conversion","The selected demo area shows a smaller land-cover change.","−21.1 ha"]};$$("[data-region]").forEach(b=>b.onclick=()=>{$$("[data-region]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const r=regions[b.dataset.region];$("#evidenceTitle").textContent=r[0];$("#evidenceDesc").textContent=r[1];$("#evidenceDelta").textContent=r[2]});$$("[data-view]").forEach(b=>b.onclick=()=>{$$("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("#showAll").onclick=()=>$$("[data-region]").forEach(x=>x.classList.add("active"))}
async function analyzeWithBackend(formData){return null}